version: "3"
services:
  web:
    image: jasonyuyu/spring-boot-app:v2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "10000:10000"
    networks:
      - webnet
networks:
  webnet:
